---
    - name: install epel-release
      action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"

    - name: delete databases
      mysql_db:
          login_user: root
          login_password: "{{ mysql_root_password }}"
          name: "{{ mysql_user_db_name }}"
          state: absent

    - name: remove mysql server
      action: "{{ ansible_pkg_mgr }} name=mariadb-server state=absent"

    - name: remove python mysql support library
      action: "{{ ansible_pkg_mgr }} name=MySQL-python state=absent"
